export const codigosPais = {
    Mexico: 'mx',
    'South Africa': 'za',
    'South Korea': 'kr',
    'Czech Republic': 'cz',
    Canada: 'ca',
    Argentina: 'ar',
    Brazil: 'br',
    Uruguay: 'uy',
    Paraguay: 'py',
    Colombia: 'co',
    Ecuador: 'ec',
    Chile: 'cl',
    Peru: 'pe',
    Bolivia: 'bo',
    Venezuela: 've',
    USA: 'us',
    'United States': 'us',
    Germany: 'de',
    France: 'fr',
    Spain: 'es',
    Portugal: 'pt',
    England: 'gb-eng',
    Italy: 'it',
    Netherlands: 'nl',
    Belgium: 'be',
    Croatia: 'hr',
    Denmark: 'dk',
    Switzerland: 'ch',
    Austria: 'at',
    Poland: 'pl',
    Serbia: 'rs',
    Morocco: 'ma',
    Senegal: 'sn',
    Tunisia: 'tn',
    Egypt: 'eg',
    Ghana: 'gh',
    Nigeria: 'ng',
    Cameroon: 'cm',
    Japan: 'jp',
    Australia: 'au',
    Iran: 'ir',
    'Saudi Arabia': 'sa',
    Qatar: 'qa',
    'Bosnia & Herzegovina': 'ba',
    Turkey: 'tr',
    'Ivory Coast': 'ci',
    Sweden: 'se',
    'New Zealand': 'nz',
    'Cape Verde': 'cv',
    Iraq: 'iq',
    Norway: 'no',
    Algeria: 'dz',
    Jordan: 'jo',
    'DR Congo': 'cd',
    Uzbekistan: 'uz',
    Panama: 'pa',
    Haiti: 'ht',
    Scotland: 'gb-sct',
    'Curaçao': 'cw',
}

export function obtenerBanderaUrl(equipo) {
    const codigo = codigosPais[equipo]
    return codigo
        ? `https://flagcdn.com/w40/${codigo}.png`
        : 'https://flagcdn.com/w40/un.png'
}
